"""empty message

Revision ID: 094e17af1a20
Revises: d2b662801a36
Create Date: 2024-05-15 18:09:38.894865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094e17af1a20'
down_revision = 'd2b662801a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_list_association')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owners', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('owners')

    op.create_table('user_list_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], name='user_list_association_list_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_list_association_user_id_fkey')
    )
    # ### end Alembic commands ###
