"""empty message

Revision ID: 34f8a3cc7bb4
Revises: c7da63d1781e
Create Date: 2024-05-29 21:30:21.336693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f8a3cc7bb4'
down_revision = 'c7da63d1781e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('poster_path',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('first_air_date',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('last_air_date',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('number_of_episodes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('number_of_seasons',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('number_of_seasons',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('number_of_episodes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_air_date',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('first_air_date',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('poster_path',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
