"""empty message

Revision ID: 6d5c2fedad4b
Revises: 
Create Date: 2024-05-14 17:48:43.144440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5c2fedad4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('overview', sa.String(length=120), nullable=False),
    sa.Column('poster_path', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.String(length=120), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('tagline', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('overview', sa.String(length=120), nullable=False),
    sa.Column('poster_path', sa.String(length=120), nullable=False),
    sa.Column('first_air_date', sa.String(length=120), nullable=False),
    sa.Column('last_air_date', sa.String(length=120), nullable=False),
    sa.Column('number_of_episodes', sa.Integer(), nullable=False),
    sa.Column('number_of_seasons', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('network', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie')
    op.drop_table('movie')
    op.drop_table('list')
    op.drop_table('user')
    # ### end Alembic commands ###
