"""empty message

Revision ID: c774d4981dff
Revises: b38b2e05b55e
Create Date: 2024-05-13 19:21:21.895679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c774d4981dff'
down_revision = 'b38b2e05b55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('overview', sa.String(length=120), nullable=False),
    sa.Column('poster_path', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.String(length=120), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('tagline', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('overview', sa.String(length=120), nullable=False),
    sa.Column('poster_path', sa.String(length=120), nullable=False),
    sa.Column('first_air_date', sa.String(length=120), nullable=False),
    sa.Column('last_air_date', sa.String(length=120), nullable=False),
    sa.Column('number_of_episodes', sa.Integer(), nullable=False),
    sa.Column('number_of_seasons', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('network', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie')
    op.drop_table('movie')
    op.drop_table('list')
    # ### end Alembic commands ###
