"""empty message

Revision ID: c7da63d1781e
Revises: 12b5ccd97928
Create Date: 2024-05-29 17:54:02.610593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7da63d1781e'
down_revision = '12b5ccd97928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
