"""empty message

Revision ID: eb0dfa8d0fda
Revises: 34f8a3cc7bb4
Create Date: 2024-05-29 21:49:33.802125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0dfa8d0fda'
down_revision = '34f8a3cc7bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.alter_column('overview',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
